### ISSUE TITLE
marble color does not appear visually

### ISSUE THREAD

**Issue by scorreia** [dmossakowski/skala3ma#26]
When viewing routes, the marble color is exactly the same as the plain color

**Comment by dmossakowski** [comment]
The fix would need to be done here: for the main route list: https://github.com/dmossakowski/skala3ma/blob/29e164894a3fe6dbc922a18cbdf7efb2ab700229/views/gym-routes.html#L354C38-L354C44

We may need to introduce color2 variable as sometimes the hold colors are blue-white, red-black, purrple-dark purple, etc.

For now it may be enough to add some kind of pattern to the color to indicate that it's not a solid. The pattern could be in darker or lighter shade of the original color.
