### ISSUE TITLE
Change the order of the menu

### ISSUE THREAD

**Issue by scorreia** [dmossakowski/skala3ma#41]
<img width="334" alt="Screenshot 2024-01-26 at 19 34 01" src="https://github.com/dmossakowski/skala3ma/assets/6770495/319802d4-2ea2-4415-a851-6bc5d065e3b3">
Change the order to "Aide, Murs, Compétitions, Activités"

**Comment by Kehinde13** [comment]
Can you assign me this

**Comment by scorreia** [comment]
@dmossakowski  we can probably cancel this issue after this commit : 
https://github.com/dmossakowski/skala3ma/commit/1ab6882e8e6d0359b0d0fc450229a419a2243879#diff-33aac6ddae373d84f4ef6358572542cc3ad545511231e1cb280202b4b7f8dc31

**Comment by dmossakowski** [comment]
Menu order changed in a different way
