### ISSUE TITLE
Feature to unsubscribe to a competition

### ISSUE THREAD

**Issue by scorreia** [dmossakowski/skala3ma#53]
Right now, we cannot unsubscribe to a competition and we cannot contact the organizer. 
Users should be able to unsubscribe easily.  

Ideally, the admin should get a notification (email? notification when connecting?...) 
so that they can contact the users on the waiting list. 

We could think to update automatically the status of the first user on the waiting list, but we need to notify them if we do that.

**Comment by dmossakowski** [comment]
We can do it only for subscribers that login using Google.. for anonymous users it's not possible.

**Comment by dmossakowski** [comment]
This feature is completed by https://github.com/dmossakowski/skala3ma/pull/58
