### ISSUE TITLE
Feature: ability to delete a list of routes from a gym

### ISSUE THREAD

**Issue by scorreia** [dmossakowski/skala3ma#68]
There are now many lists of routes in the Nanterre gym. 
We should probably delete some of them. 

When deleting a list of route, this should not impact past activities (maybe, we simply deactivate the list of routes and hide it everywhere if we cannot delete it easily).

**Comment by scorreia** [comment]
although the admin offers the ability to delete routes, it does not work (as of today)

**Comment by dmossakowski** [comment]
It's done as of Dec 8 2024. The deletion of routes is possible in the batch edit view and also in the raw admin.
