### ISSUE TITLE
Ask for confirmation before delete a gym

### ISSUE THREAD

**Issue by scorreia** [dmossakowski/skala3ma#9]
There should be one or two confirmation before deleting a gym. 
Because there is no undo button and the delete button can be hit by mistake

**Comment by dmossakowski** [comment]
There is additional check before deleting a competition. A competition can only be deleted if it has 0 climbers registered and is in 'Created' state. 

def competition_can_be_deleted(competition):
    climbers = competition.get('climbers')
    
    if climbers is not None and len(climbers)>0:
        return False
    if competition['status'] != competition_status_created:
        return False

    return True

**Comment by scorreia** [comment]
Indeed. I did not see that. 
Actually, I was expecting an error message eventually.

**Comment by dmossakowski** [comment]
I'm going to close this as I think there are enough safeguards to avoid deleting competition by accident (you have to remove all registered users and set it to Created status)
